steps:
# Use Kaniko cache to build Docker container image for Hugo
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=hugo.Dockerfile
  - --destination=gcr.io/$PROJECT_ID/hugo
  - --cache=true

# Use Kaniko cache to build Docker container image for Firebase Tools
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --dockerfile=firebase.Dockerfile
    - --destination=gcr.io/$PROJECT_ID/firebase
    - --cache=true

# Build the website with Hugo
- name: 'gcr.io/$PROJECT_ID/hugo'

# Deploy to Firebase Hosting
- name: 'gcr.io/$PROJECT_ID/firebase'
  args:
    - deploy
    - --project $PROJECT_ID
    - --only hosting